version: '3.3'
services:

  # Nginx Reverse Proxy
  nginx:
    container_name: vescd-nginx
    image: nginx:1.13.12-alpine
    ports:
      - "8080:80"
      - "9229:9229"
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d/

  # Express
  express:
    container_name: vescd-express
    build:
      context: ./docker/express
    volumes:
      - ./express:/app
      - /app/node_modules
    command: npm run dev
  
  # Database
  db:
    container_name: vescd-db
    image: postgres:12
    environment:
      - POSTGRES_USER=vescd-access
      - POSTGRES_PASSWORD=whateverItworks
      - POSTGRES_DB=vescd
    ports:
      - 5432:5432
    volumes:
      - ./vescd-db:/var/lib/postgresql/data
  
  # pgAdmin
  pgadmin:
    container_name: vescd-pgadmin
    image: dpage/pgadmin4:4.13
    environment:
      PGADMIN_DEFAULT_EMAIL: demo@email.com
      PGADMIN_DEFAULT_PASSWORD: p@ssw0rd
    ports:
      - 8081:80

  # RabbitMQ
  rabbitmq:
    container_name: vescd-rabbitmq
    image: rabbitmq:management-alpine:3.8.0
    tty: true
    ports:
        - "15672:15672"
        - "5672:5672"