FROM node:12-alpine

RUN apk add tzdata && \
    cp /usr/share/zoneinfo/Asia/Bangkok /etc/localtime && \
    echo "Asia/Bangkok" >  /etc/timezone && \
    apk del tzdata

# Preparing Dependencies
WORKDIR /app
COPY ./package.json ./
RUN npm install

# Copy Files
COPY . .
CMD ["npm", "run", "dev"]

EXPOSE 3000