version: '3.3'
services:

  # Nginx Reverse Proxy
  nginx:
    container_name: vescd-nginx
    image: nginx:1.13.12-alpine
    ports:
      - "8080:80"
      - "9229:9229"
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d/

  # Express
  express:
    container_name: vescd-express
    build:
      context: ./docker/express
    volumes:
      - ./express:/app
      - /app/node_modules
    command: npm run dev
  
  # Database
  db:
    container_name: vescd-db
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./vescd-db:/var/lib/mysql
    environment:
      MYSQL_USER: vescd-access
      MYSQL_PASSWORD: whateverItworks
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: vescd
  
  # adminer
  adminer:
    container_name: vescd-adminer
    image: adminer
    restart: always
    ports:
      - 8081:8080

  # RabbitMQ
  rabbitmq:
    container_name: vescd-rabbitmq
    image: rabbitmq:3.8.0-management-alpine
    tty: true
    ports:
        - "15672:15672"
        - "5672:5672"