version: '3.3'
services:

  # Nginx Reverse Proxy
  nginx:
    container_name: vescd-nginx
    image: nginx:1.13.12-alpine
    ports:
      - "3000:80"
      - "9229:9229"
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d/

  # Express
  express:
    container_name: vescd-express
    build:
      context: ./docker/express
    volumes:
      - ./express:/app
      - /app/node_modules
    command: npm run dev
  
  # Database
  db:
    container_name: vescd-db
    image: postgres
    environment:
      - POSTGRES_USER=vescd-access
      - POSTGRES_PASSWORD=whateverItworks
      - POSTGRES_DB=vescd
    volumes:
      - ./vescd-db:/var/lib/postgresql/data
  
  # pgAdmin
  pgadmin:
    container_name: vescd-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: demo@email.com
      PGADMIN_DEFAULT_PASSWORD: p@ssw0rd
    ports:
      - 3001:80